library(knitr)
library(dplyr)
library(readr)
library(rvest)
library(gsubfn)
library(ggplot2)
library(reshape2)
library(shiny)
library(RCurl)
library(XML)
#library(rJava)
#library(xlsx)
library(rworldmap)
library(rworldxtra)
library(maptools)
library(rgdal)
library(ggmap)
library(ggvis)
library(RColorBrewer)
library(geojsonio)
library(spdplyr)
library(rmapshaper)
library(leaflet)
library(leafletR)
library(sp)
library(rgeos)
#library(gpclib) 

# Uvozimo funkcije za pobiranje in uvoz zemljevida.
source("lib/uvozi.zemljevid.r", encoding = "UTF-8")
